apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: lms-books
type: Opaque
data:
  # Base64 encoded values (postgres / password)
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_DB: Ym9va3NkYg==
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: lms-books
type: Opaque
data:
  # Base64 encoded values (guest / guest)
  RABBITMQ_DEFAULT_USER: Z3Vlc3Q=
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q=
